### ISSUE TITLE
cuDNN error: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by MalayAgr** [DIAGNijmegen/StreamingCNN#6]
Hi. I am running into this issue specifically in the backward pass of `StreamingCNN`.

This is happening in the function [`backward(ctx, grad_output)`](https://github.com/DIAGNijmegen/StreamingCNN/blob/41a3475c580390405971fd8aaeadf998f387f396/scnn.py#L109), when it calls [`cpp_functions.backward_input`](https://github.com/DIAGNijmegen/StreamingCNN/blob/41a3475c580390405971fd8aaeadf998f387f396/scnn.py#L133).

In the backtrace, the argument highlighted is `torch.backends.cudnn.deterministic` but I think the error occurs for some other argument. Here's the backtrace for reference:

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_33/2483119126.py in <module>
      4     streamer=streamer,
      5     final_net=final_net,
----> 6     lr=LR,
      7 )

/tmp/ipykernel_33/1161120236.py in train(train_loader, val_loader, streamer, final_net, lr)
     17             final_net=final_net,
     18             criterion=criterion,
---> 19             optimizer=optimizer,
     20         )
     21 

/tmp/ipykernel_33/2582985019.py in train_one_epoch(data_loader, streamer, final_net, criterion, optimizer)
     35             # The function requires the images
     36             # And the gradient of loss wrt its output
---> 37             streamer.backward(images, streamer_op.grad)
     38 
     39             optimizer.step()

/kaggle/working/scnn.py in backward(self, image, grad)
   1074                     ]
   1075 
-> 1076                 trimmed_output.backward(trimmed_grad)
   1077 
   1078                 # Memory management

/opt/conda/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    193                 products. Defaults to ``False``.
    194         """
--> 195         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    196 
    197     def register_hook(self, hook):

/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     97     Variable._execution_engine.run_backward(
     98         tensors, grad_tensors, retain_graph, create_graph,
---> 99         allow_unreachable=True)  # allow_unreachable flag
    100 
    101 

/opt/conda/lib/python3.7/site-packages/torch/autograd/function.py in apply(self, *args)
     75 
     76     def apply(self, *args):
---> 77         return self._forward_cls.backward(self, *args)
     78 
     79 

/kaggle/working/scnn.py in backward(ctx, grad_output)
    182                     groups,
    183                     torch.backends.cudnn.benchmark,
--> 184                    torch.backends.cudnn.deterministic,
    185                 )
    186         else:

RuntimeError: cuDNN error: CUDNN_STATUS_BAD_PARAM (set at /pytorch/aten/src/ATen/cudnn/Descriptors.h:157)
```

I've tried setting the two `.cudnn` values manually to `False`/`True`, both while calling the function itself and by executing `torch.backends.cudnn.<x> = False/True` but I get the same error, leading me to believe that these aren't the problematic parameters.

For context:

- I am using PyTorch 1.4.0.
- I have binary images of `4000x4000`. Initially, I added only a single channel so that each image is `(1, 4000, 4000)` but then tried it with `(3, 4000, 4000)`. The error doesn't go away.
- I am using `torch.float32` for my images.

**Comment by MalayAgr** [comment]
Update: I've tried converting the shape parameters to `tuple`. It still doesn't work.

**Comment by MalayAgr** [comment]
Hi! I found the issue! The problem was that the stride and padding arguments were in the wrong order. The function expects padding before stride. Reversing the order fixed it!

**Comment by hanspinckaers** [comment]
~~Strange, it looks like it should be the right order:~~

https://github.com/pytorch/pytorch/blob/dab5e2a23ed387046d99f825e0d9a45bd58fccaa/aten/src/ATen/native/cudnn/ConvShared.cpp#L373

Edit: see https://github.com/DIAGNijmegen/StreamingCNN/issues/6#issuecomment-1066599545

**Comment by hanspinckaers** [comment]
~~Even more strange, in this repo it looks like the wrong order:~~
~~https://github.com/jordan-g/PyTorch-cuDNN-Convolution~~

~~Did you rename this repo's `conv2d_backward.cpp` file to `cpp_functions.cpp`? That is a bug that is in the current code.~~

**Comment by hanspinckaers** [comment]
I thought you were talking about `cpp_functions.backward`. You are correct that `cpp_functions.backward_input` is in the wrong order! This could explain why I needed to fall back to pytorch torch.nn.grad.conv2d_input for certain stride/padding combination 😄

**Comment by hanspinckaers** [comment]
Fixed now!
